# Generated by Django 2.2.5 on 2020-08-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='total_organizations_organization_uploaded',
            field=models.IntegerField(default=0, help_text='The total number of organizations who have uploaded at least one organizational document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_organizations_private_uploaded',
            field=models.IntegerField(default=0, help_text='The total number of organizations who have uploaded at least one private document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_organizations_public_uploaded',
            field=models.IntegerField(default=0, help_text='The total number of organizations who have uploaded at least one public document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_organizations_uploaded',
            field=models.IntegerField(default=0, help_text='The total number of organizations who have uploaded at least one document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_users_organization_uploaded',
            field=models.IntegerField(default=0, help_text='The total number of users who have uploaded at least one organizational document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_users_private_uploaded',
            field=models.IntegerField(default=0, help_text='The total number of users who have uploaded at least one private document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_users_public_uploaded',
            field=models.IntegerField(default=0, help_text='The total number of users who have uploaded at least one public document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_users_uploaded',
            field=models.IntegerField(default=0, help_text='The total number of users who have uploaded at least one document'),
            preserve_default=False,
        ),
    ]
