version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_solr_data: {}
  local_solr_test_data: {}
  local_minio_data: {}

services:

  documentcloud_django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: documentcloud_local_django
    depends_on:
      - documentcloud_postgres
      - documentcloud_redis
      - documentcloud_processing_redis
      - documentcloud_minio
      - documentcloud_solr
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    networks:
      default:
        aliases:
          - api.dev.documentcloud.org
          - api.dev.documentcloud.local
      squarelet_default:
        aliases:
          - api.dev.documentcloud.org
          - api.dev.documentcloud.local


  documentcloud_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: documentcloud_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  documentcloud_redis:
    image: redis:5.0

  documentcloud_processing_redis:
    image: redis:5.0

  documentcloud_minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    volumes:
      - local_minio_data:/data
    ports:
      - "9000:9000"
    command: server /data
    env_file:
      - ./.envs/.local/.django
    networks:
      default:
        aliases:
          - minio.documentcloud.org

  documentcloud_solr:
    image: solr:8.3
    ports:
      - "8983:8983"
    volumes:
      - local_solr_data:/var/solr
      - ./config/solr:/config
      - ./config/solr/lib:/opt/solr-8.3.0/lib
    command:
      - solr-precreate
      - documentcloud
      - /config

  documentcloud_test_solr:
    image: solr:8.3
    ports:
      - "8984:8983"
    volumes:
      - local_solr_test_data:/var/solr
      - ./config/solr:/config
      - ./config/solr/lib:/opt/solr-8.3.0/lib
    command:
      - solr-precreate
      - documentcloud_test
      - /config

  documentcloud_celeryworker:
    <<: *django
    image: documentcloud_local_celeryworker
    depends_on:
      - documentcloud_redis
      - documentcloud_processing_redis
      - documentcloud_postgres
    command: /start-celeryworker
    networks:
      - default
      - squarelet_default

  documentcloud_celerybeat:
    <<: *django
    image: documentcloud_local_celerybeat
    depends_on:
      - documentcloud_redis
      - documentcloud_processing_redis
      - documentcloud_postgres
    command: /start-celerybeat
    networks:
      - default
      - squarelet_default

networks:
  squarelet_default:
    external: true
