version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  #local_solr_data: {}
  #local_solr_test_data: {}
  #local_minio_data1: {}
  #local_minio_data2: {}

services:

  documentcloud_django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: documentcloud_local_django
    depends_on:
      - documentcloud_postgres
      - documentcloud_redis
      - documentcloud_processing_redis
      #- documentcloud_solr
      #- documentcloud_minio
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    networks:
      default:
        aliases:
          - api.dev.documentcloud.org
      squarelet_default:
        aliases:
          - api.dev.documentcloud.org

  documentcloud_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: documentcloud_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  documentcloud_redis:
    image: redis:5.0

  documentcloud_processing_redis:
    image: redis:5.0

  #documentcloud_minio:
  #  image: minio/minio:RELEASE.2019-09-11T19-53-16Z
  #  volumes:
  #    - local_minio_data1:/data1
  #    - local_minio_data2:/data2
  #  ports:
  #    - "9000:9000"
  #  environment:
  #    MINIO_ACCESS_KEY: minio
  #    MINIO_SECRET_KEY: minio123
  #  command: server http://documentcloud_minio/data{1...2}
  #  healthcheck:
  #    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #    interval: 30s
  #    timeout: 20s
  #    retries: 3

  # add solr and test solr images in

  documentcloud_celeryworker:
    <<: *django
    image: documentcloud_local_celeryworker
    depends_on:
      - documentcloud_redis
      - documentcloud_processing_redis
      - documentcloud_postgres
    command: /start-celeryworker
    networks:
      - default
      - squarelet_default

  documentcloud_celerybeat:
    <<: *django
    image: documentcloud_local_celerybeat
    depends_on:
      - documentcloud_redis
      - documentcloud_processing_redis
      - documentcloud_postgres
    command: /start-celerybeat
    networks:
      - default
      - squarelet_default

networks:
  squarelet_default:
    external: true
