# Generated by Django 3.2.9 on 2022-01-25 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.SQUARELET_ORGANIZATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The plugin's name", max_length=255, verbose_name='name')),
                ('repository', models.CharField(help_text="The plugin's GitHub repository", max_length=140, verbose_name='repository')),
                ('github_token', models.CharField(help_text="The token to access the plugin's GitHub repository", max_length=40, verbose_name='github token')),
                ('parameters', models.JSONField(help_text='The parameters for this plugin', verbose_name='parameters')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the document was created', verbose_name='created at')),
                ('updated_at', documentcloud.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the document was last updated', verbose_name='updated at')),
                ('organization', models.ForeignKey(help_text='The organization this plugin was created within', on_delete=django.db.models.deletion.PROTECT, related_name='plugins', to=settings.SQUARELET_ORGANIZATION_MODEL, verbose_name='organization')),
                ('user', models.ForeignKey(help_text='The user who created this plugin', on_delete=django.db.models.deletion.PROTECT, related_name='plugins', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
