# Generated by Django 3.2.9 on 2022-02-16 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique ID to track plugin runs', unique=True, verbose_name='UUID')),
                ('run_id', models.IntegerField(help_text='The GitHub Action run_id for this run', null=True, unique=True, verbose_name='run_id')),
                ('status', models.CharField(default='queued', help_text='The status of this run', max_length=25, verbose_name='status')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the document was created', verbose_name='created at')),
                ('updated_at', documentcloud.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the document was last updated', verbose_name='updated at')),
                ('plugin', models.ForeignKey(help_text='The plugin which was ran', on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='plugins.plugin', verbose_name='plugin')),
                ('user', models.ForeignKey(help_text='The user who ran this plugin', on_delete=django.db.models.deletion.PROTECT, related_name='plugin_runs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
