# Generated by Django 3.2.9 on 2022-02-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_pluginrun_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginrun',
            name='file_name',
            field=models.CharField(default='', help_text='Path to uploaded file on S3', max_length=255, verbose_name='file_name'),
        ),
    ]
