# Generated by Django 3.2.9 on 2022-02-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_pluginrun_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginrun',
            name='message',
            field=models.CharField(default='', help_text='A progress message for the user while the run is in progress', max_length=255, verbose_name='message'),
        ),
    ]
