# Generated by Django 3.2.9 on 2023-02-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='localized_names',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
