# Generated by Django 3.2.9 on 2023-02-01 18:14

from django.db import migrations
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20230201_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=documentcloud.core.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the entity was created', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='updated_at',
            field=documentcloud.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the entitywas last updated', verbose_name='updated at'),
        ),
    ]
