# Generated by Django 3.2.9 on 2023-02-06 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0004_alter_entity_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entity',
            name='wikidata_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
