# Generated by Django 3.2.9 on 2023-02-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20230206_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
