# Generated by Django 3.2.9 on 2023-02-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0051_auto_20230214_1451'),
        ('entities', '0006_entity_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField(default=0.0, help_text='The relevance of this entity', verbose_name='relevance')),
                ('occurrences', models.JSONField(default=dict, help_text='Locations of entity in this document', verbose_name='occurrences')),
                ('document', models.ForeignKey(help_text='The document this entity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='documents.document', verbose_name='document')),
                ('entity', models.ForeignKey(help_text='The entity which appears in the document', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entities.entity', verbose_name='entity')),
            ],
        ),
    ]
