# Generated by Django 3.2.9 on 2023-02-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_entityoccurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Extra data about this entity'),
        ),
    ]
