# Generated by Django 3.2.9 on 2023-02-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20230214_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='entity',
            name='localized_names',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='entity',
            name='wikipedia_url',
            field=models.JSONField(default=dict),
        ),
    ]
