# Generated by Django 3.2.9 on 2023-02-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_auto_20230214_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
