# Generated by Django 3.2.9 on 2023-02-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_alter_entity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
