# Generated by Django 3.2.9 on 2023-02-23 15:03

# Django
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

# Third Party
import parler.fields
import parler.models

# DocumentCloud
import documentcloud.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0051_auto_20230214_1451"),
        ("entities", "0012_alter_entity_wikidata_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="description",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="localized_names",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="name",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="wikipedia_url",
        ),
        migrations.AlterField(
            model_name="entity",
            name="metadata",
            field=models.JSONField(
                default=dict,
                help_text="Extra data about this entity",
                verbose_name="metadata",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="updated_at",
            field=documentcloud.core.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Timestamp of when the entity was last updated",
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="wikidata_id",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                unique=True,
                verbose_name="wikidata id",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entityoccurrence",
            unique_together={("document", "entity")},
        ),
        migrations.CreateModel(
            name="EntityTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=500, verbose_name="name"),
                ),
                (
                    "wikipedia_url",
                    models.URLField(blank=True, verbose_name="wikipedia url"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="entities.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "entity Translation",
                "db_table": "entities_entity_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
