# Generated by Django 3.2.9 on 2023-02-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0013_auto_20230223_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.AlterField(
            model_name='entitytranslation',
            name='wikipedia_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='wikipedia url'),
        ),
    ]
