# Generated by Django 2.2.5 on 2019-09-12 11:06

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_auto_20190911_1726'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.IntegerField(choices=[(0, 'Public'), (1, 'Organization'), (2, 'Private'), (3, 'Invisible')])),
                ('status', models.IntegerField(choices=[(0, 'Success'), (1, 'Readable'), (2, 'Pending'), (3, 'Error')], default=2)),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('language', models.CharField(blank=True, choices=[('ara', 'Arabic'), ('zho', 'Chinese (Simplified)'), ('tra', 'Chinese (Traditional)'), ('hrv', 'Croatian'), ('dan', 'Danish'), ('nld', 'Dutch'), ('eng', 'English'), ('fra', 'French'), ('deu', 'German'), ('heb', 'Hebrew'), ('hun', 'Hungarian'), ('ind', 'Indonesian'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nor', 'Norwegian'), ('por', 'Portuguese'), ('ron', 'Romanian'), ('rus', 'Russian'), ('spa', 'Spanish'), ('swe', 'Swedish'), ('ukr', 'Ukrainian')], help_text='The language of the document.  Will be used to determine what OCR package to use for files that require OCR processing.', max_length=3)),
                ('source', models.CharField(blank=True, help_text='The source who produced the document', max_length=1000)),
                ('description', models.TextField(blank=True, help_text='A paragraph of detailed description')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_at', documentcloud.core.fields.AutoLastModifiedField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='organizations.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(db_index=True)),
                ('text', models.TextField()),
                ('aspect_ratio', models.FloatField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.Document')),
            ],
            options={
                'ordering': ('document', 'page_number'),
            },
        ),
    ]
