# Generated by Django 2.2.5 on 2019-09-17 17:23

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.IntegerField(choices=[(0, 'Public'), (1, 'Organization'), (2, 'Private'), (3, 'Invisible')], help_text='Designates who may access this document by default', verbose_name='access')),
                ('status', models.IntegerField(choices=[(0, 'Success'), (1, 'Readable'), (2, 'Pending'), (3, 'Error')], default=2, help_text='The processing status of this document', verbose_name='status')),
                ('title', models.CharField(db_index=True, help_text="The document's title", max_length=255, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='A slug for the document which may be used in a URL', populate_from='title', verbose_name='slug')),
                ('page_count', models.IntegerField(db_index=True, default=0, help_text='Number of pages in this document', verbose_name='page count')),
                ('language', models.CharField(blank=True, choices=[('ara', 'Arabic'), ('zho', 'Chinese (Simplified)'), ('tra', 'Chinese (Traditional)'), ('hrv', 'Croatian'), ('dan', 'Danish'), ('nld', 'Dutch'), ('eng', 'English'), ('fra', 'French'), ('deu', 'German'), ('heb', 'Hebrew'), ('hun', 'Hungarian'), ('ind', 'Indonesian'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nor', 'Norwegian'), ('por', 'Portuguese'), ('ron', 'Romanian'), ('rus', 'Russian'), ('spa', 'Spanish'), ('swe', 'Swedish'), ('ukr', 'Ukrainian')], help_text='The language of the document.  Will be used to determine what OCR package to use for files that require OCR processing.', max_length=3, verbose_name='language')),
                ('source', models.CharField(blank=True, help_text='The source who produced the document', max_length=1000, verbose_name='source')),
                ('description', models.TextField(blank=True, help_text='A paragraph of detailed description', verbose_name='description')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the document was created', verbose_name='created at')),
                ('updated_at', documentcloud.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the document was last updated', verbose_name='updated at')),
                ('organization', models.ForeignKey(help_text='The organization this document was created within', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='organizations.Organization', verbose_name='organization')),
                ('user', models.ForeignKey(help_text='The user who created this document', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(db_index=True, help_text='The page number', verbose_name='page number')),
                ('text', models.TextField(help_text='The text on this page', verbose_name='text')),
                ('aspect_ratio', models.FloatField(blank=True, help_text='The aspect ratio for displaying this page', null=True)),
                ('document', models.ForeignKey(help_text='The document this page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.Document', verbose_name='document')),
            ],
            options={
                'ordering': ('document', 'page_number'),
            },
        ),
    ]
