# Generated by Django 2.2.5 on 2019-09-25 18:16

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text='A slug for the document which may be used in a URL', max_length=255, populate_from='title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(db_index=True, help_text="The document's title", max_length=1000, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(help_text='Which page this note appears on', verbose_name='page number')),
                ('access', models.IntegerField(choices=[(0, 'Public'), (1, 'Organization'), (2, 'Private'), (3, 'Invisible')], help_text='Designates who may access this document by default', verbose_name='access')),
                ('title', models.TextField(help_text='A title for the note', verbose_name='title')),
                ('content', models.TextField(help_text='The contents of the note', verbose_name='content')),
                ('top', models.PositiveSmallIntegerField(help_text='The top coordinate of the note in percantage of the page size', verbose_name='top')),
                ('left', models.PositiveSmallIntegerField(help_text='The left coordinate of the note in percantage of the page size', verbose_name='left')),
                ('bottom', models.PositiveSmallIntegerField(help_text='The bottom coordinate of the note in percantage of the page size', verbose_name='bottom')),
                ('right', models.PositiveSmallIntegerField(help_text='The right coordinate of the note in percantage of the page size', verbose_name='right')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the note was created', verbose_name='created at')),
                ('updated_at', documentcloud.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the note was last updated', verbose_name='updated at')),
                ('document', models.ForeignKey(help_text='The document this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='documents.Document', verbose_name='document')),
                ('organization', models.ForeignKey(help_text='The organization this note was created within', on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='organizations.Organization', verbose_name='organization')),
                ('user', models.ForeignKey(help_text='The user who created this note', on_delete=django.db.models.deletion.PROTECT, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
