# Generated by Django 2.2.5 on 2019-09-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20190925_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='bottom',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The bottom coordinate of the note in percantage of the page size', null=True, verbose_name='bottom'),
        ),
        migrations.AlterField(
            model_name='note',
            name='left',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The left coordinate of the note in percantage of the page size', null=True, verbose_name='left'),
        ),
        migrations.AlterField(
            model_name='note',
            name='right',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The right coordinate of the note in percantage of the page size', null=True, verbose_name='right'),
        ),
        migrations.AlterField(
            model_name='note',
            name='top',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The top coordinate of the note in percantage of the page size', null=True, verbose_name='top'),
        ),
    ]
