# Generated by Django 2.2.5 on 2019-09-25 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('person', 'Person'), ('organization', 'Organization'), ('place', 'Place'), ('term', 'Term'), ('email', 'Email'), ('phone', 'Phone'), ('city', 'City'), ('state', 'State'), ('country', 'Country')], help_text='The kind of entity', max_length=40, verbose_name='kind')),
                ('value', models.CharField(help_text='The value of this entity', max_length=255, verbose_name='value')),
                ('relevance', models.FloatField(default=0.0, help_text='The relevance of this entity', verbose_name='relevance')),
                ('calais_id', models.CharField(blank=True, help_text='The ID from open calais', max_length=40, verbose_name='calais id')),
                ('occurrences', models.TextField(blank=True, help_text='Where this entity occurs in the document', verbose_name='occurrences')),
                ('document', models.ForeignKey(help_text='The document this entity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='documents.Document', verbose_name='document')),
            ],
        ),
        migrations.CreateModel(
            name='EntityDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date', verbose_name='date')),
                ('occurrences', models.TextField(blank=True, help_text='Where this entity occurs in the document', verbose_name='occurrences')),
                ('document', models.ForeignKey(help_text='The document this entity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='documents.Document', verbose_name='document')),
            ],
            options={
                'unique_together': {('document', 'date')},
            },
        ),
    ]
