# Generated by Django 2.2.5 on 2019-10-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_entity_entitydate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('process_document', 'Document processor - can set `page_count`, `page_spec`, and `status` through the API'),)},
        ),
        migrations.AddField(
            model_name='document',
            name='page_spec',
            field=models.TextField(blank=True, help_text='A cached and compressed specification of each pages dimensions', verbose_name='page specification'),
        ),
    ]
