# Generated by Django 2.2.5 on 2019-10-24 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20191021_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the error occured', verbose_name='created at')),
                ('message', models.TextField(help_text='The error message', verbose_name='message')),
                ('document', models.ForeignKey(help_text='The document this page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='documents.Document', verbose_name='document')),
            ],
        ),
    ]
