# Generated by Django 2.2.5 on 2019-11-07 20:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documenterror'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(0, 'Success'), (1, 'Readable'), (2, 'Pending'), (3, 'Error'), (4, 'No file')], default=4, help_text='The processing status of this document', verbose_name='status'),
        ),
    ]
