# Generated by Django 2.2.5 on 2019-11-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20191106_2010'),
        ('documents', '0008_auto_20191107_2031'),
    ]

    operations = [
    ]
