# Generated by Django 2.2.5 on 2019-12-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_merge_20191112_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='solr_dirty',
            field=models.BooleanField(default=False, help_text='Tracks if the Solr Index is out of date with the SQL model', verbose_name='solr dirty'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(0, 'Success'), (1, 'Readable'), (2, 'Pending'), (3, 'Error'), (4, 'No file'), (5, 'Deleted')], default=4, help_text='The processing status of this document', verbose_name='status'),
        ),
    ]
