# Generated by Django 2.2.5 on 2020-01-28 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20191211_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('created_at',), 'permissions': (('process_document', 'Document processor - can set `page_count`, `page_spec`, and `status` through the API'),)},
        ),
        migrations.AlterModelOptions(
            name='documenterror',
            options={'ordering': ('document', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('document', '-relevance')},
        ),
        migrations.AlterModelOptions(
            name='entitydate',
            options={'ordering': ('document', 'date')},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('document', 'page_number')},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('document', 'page_number')},
        ),
        migrations.RemoveField(
            model_name='note',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='note',
            name='left',
        ),
        migrations.RemoveField(
            model_name='note',
            name='right',
        ),
        migrations.RemoveField(
            model_name='note',
            name='top',
        ),
        migrations.AddField(
            model_name='note',
            name='x1',
            field=models.FloatField(blank=True, help_text='The left-most coordinate of the note in percantage of the page size', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='x1'),
        ),
        migrations.AddField(
            model_name='note',
            name='x2',
            field=models.FloatField(blank=True, help_text='The right-most coordinate of the note in percantage of the page size', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='x2'),
        ),
        migrations.AddField(
            model_name='note',
            name='y1',
            field=models.FloatField(blank=True, help_text='The top-most coordinate of the note in percantage of the page size', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='y1'),
        ),
        migrations.AddField(
            model_name='note',
            name='y2',
            field=models.FloatField(blank=True, help_text='The bottom-most coordinate of the note in percantage of the page size', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='y2'),
        ),
    ]
