# Generated by Django 2.2.5 on 2020-02-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20200205_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.PositiveIntegerField(db_index=True, help_text='The page number', verbose_name='page number'),
        ),
        migrations.AlterField(
            model_name='section',
            name='page_number',
            field=models.PositiveIntegerField(help_text='Which page this section appears on', verbose_name='page number'),
        ),
    ]
