# Generated by Django 2.2.5 on 2020-02-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20200210_1849'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('document', 'page_number')},
        ),
    ]
