# Generated by Django 2.2.5 on 2020-02-11 16:51

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("documents", "0014_auto_20200210_1900")]

    operations = [
        migrations.RunSQL(
            "ALTER SEQUENCE documents_document_id_seq RESTART WITH 10000000"
        )
    ]
