# Generated by Django 2.2.5 on 2020-02-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20200211_1651'),
        ('documents', '0015_auto_20200213_1650'),
    ]

    operations = [
    ]
