# Generated by Django 2.2.5 on 2020-02-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_merge_20200213_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='calais_id',
            field=models.CharField(blank=True, help_text='Open Calais identifier', max_length=40, verbose_name='calais id'),
        ),
        migrations.AddField(
            model_name='document',
            name='char_count',
            field=models.PositiveIntegerField(default=0, help_text='The number of characters in the document', verbose_name='character count'),
        ),
        migrations.AddField(
            model_name='document',
            name='detected_remote_url',
            field=models.URLField(blank=True, help_text='Automatically detected URL where this article is embedded', max_length=1024, verbose_name='detected remote url'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA1 digest of the file contents', max_length=40, verbose_name='file hash'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='The size of the underlying file', verbose_name='file size'),
        ),
        migrations.AddField(
            model_name='document',
            name='hit_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this document has been viewed', verbose_name='hit count'),
        ),
        migrations.AddField(
            model_name='document',
            name='original_extension',
            field=models.CharField(default='pdf', help_text='The original extension of the underlying file', max_length=255, verbose_name='original extension'),
        ),
        migrations.AddField(
            model_name='document',
            name='public_note_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of public notes on this document', verbose_name='public note count'),
        ),
        migrations.AddField(
            model_name='document',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Date the document was first made public', null=True, verbose_name='publication date'),
        ),
        migrations.AddField(
            model_name='document',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled time to make document public', null=True, verbose_name='publish at'),
        ),
        migrations.AddField(
            model_name='document',
            name='related_article',
            field=models.URLField(blank=True, help_text='Article this document pertains to', max_length=1024, verbose_name='related article'),
        ),
        migrations.AddField(
            model_name='document',
            name='remote_url',
            field=models.URLField(blank=True, help_text='URL where this article is embedded', max_length=1024, verbose_name='remote url'),
        ),
        migrations.AddField(
            model_name='document',
            name='text_changed',
            field=models.BooleanField(default=False, help_text='User manually changed the text', verbose_name='text changed'),
        ),
    ]
