# Generated by Django 2.2.5 on 2020-03-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_auto_20200226_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='document',
            field=models.ForeignKey(db_constraint=False, help_text='The document this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='documents.Document', verbose_name='document'),
        ),
    ]
