# Generated by Django 2.2.5 on 2020-04-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_auto_20200226_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='remote_url',
            new_name='published_url',
        ),
    ]
