# Generated by Django 2.2.5 on 2020-04-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_auto_20200405_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='published_url',
            field=models.URLField(blank=True, help_text='URL where this article is embedded', max_length=1024, verbose_name='published url'),
        ),
    ]
