# Generated by Django 2.2.5 on 2020-04-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_auto_20200405_1736'),
        ('documents', '0018_auto_20200311_1936'),
    ]

    operations = [
    ]
