# Generated by Django 2.2.5 on 2020-04-29 01:21

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_merge_20200407_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_duplicates=True, blank=True, editable=False, help_text='A slug for the document which may be used in a URL', max_length=255, populate_from='title', verbose_name='slug'),
        ),
    ]
