# Generated by Django 2.2.5 on 2020-04-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_auto_20200429_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(help_text='A slug for the document which may be used in a URL', max_length=255, verbose_name='slug'),
        ),
    ]
