# Generated by Django 2.2.5 on 2020-05-25 19:42

# Django
from django.db import migrations

# Standard Library
import re

# Third Party
from unidecode import unidecode


def fix_data_keys(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    for document in Document.objects.exclude(data={}):
        document.data = {
            re.sub(r"[^A-Za-z0-9_-]", "-", unidecode(k)): v
            for k, v in document.data.items()
        }
        document.save()


class Migration(migrations.Migration):

    dependencies = [("documents", "0022_auto_20200430_1411")]

    operations = [migrations.RunPython(fix_data_keys, migrations.RunPython.noop)]
