# Generated by Django 2.2.5 on 2020-08-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_auto_20200805_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitydate',
            name='document',
            field=models.ForeignKey(db_constraint=False, help_text='The document this entity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='documents.Document', verbose_name='document'),
        ),
    ]
