# Generated by Django 2.2.5 on 2020-09-30 19:02

from django.db import migrations, models
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_auto_20200807_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedDocument',
            fields=[
                ('id', models.IntegerField(help_text='The ID of the document that was deleted', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the document was deleted', verbose_name='created at')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
