# Generated by Django 2.2.5 on 2020-10-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_deleteddocument'),
        ('documents', '0028_auto_20200925_2001'),
    ]

    operations = [
    ]
