# Generated by Django 2.2.5 on 2020-12-11 14:52

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("documents", "0029_merge_20201001_1908")]

    operations = [migrations.RenameModel("Entity", "LegacyEntity")]
