# Generated by Django 2.2.5 on 2020-12-15 18:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_auto_20201211_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this entity', max_length=255, verbose_name='name')),
                ('kind', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Person'), (2, 'Location'), (3, 'Organization'), (4, 'Event'), (5, 'Work_Of_Art'), (6, 'Consumer_Good'), (7, 'Other'), (9, 'Phone_Number'), (10, 'Address'), (11, 'Date'), (12, 'Number'), (13, 'Price')], help_text='Categorization of this entity', verbose_name='kind')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Extra data asociated with this entity', verbose_name='metadata')),
            ],
        ),
        migrations.AlterField(
            model_name='legacyentity',
            name='document',
            field=models.ForeignKey(db_constraint=False, help_text='The document this entity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_entities', to='documents.Document', verbose_name='document'),
        ),
        migrations.CreateModel(
            name='EntityOccurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField(default=0.0, help_text='The relevance of this entity', verbose_name='relevance')),
                ('occurences', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Extra data asociated with this entity', verbose_name='occurences')),
                ('document', models.ForeignKey(help_text='The document this entity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='documents.Document', verbose_name='document')),
                ('entity', models.ForeignKey(help_text='The entity which appears in the document', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='documents.Entity', verbose_name='entity')),
            ],
        ),
    ]
