# Generated by Django 2.2.5 on 2020-12-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_auto_20201215_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='mid',
            field=models.CharField(blank=True, help_text='The Google Knowledge Graph ID for this entity', max_length=13, verbose_name='knowledge graph id'),
        ),
        migrations.AddField(
            model_name='entity',
            name='wikipedia_url',
            field=models.URLField(blank=True, help_text='The URL to the Wikipedia entry for this entity', verbose_name='wikipedia url'),
        ),
    ]
