# Generated by Django 2.2.5 on 2020-12-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_auto_20201222_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityOccurence',
            new_name='EntityOccurrence',
        ),
    ]
