# Generated by Django 2.2.5 on 2020-12-23 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_auto_20201223_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityoccurrence',
            old_name='occurences',
            new_name='occurrences',
        ),
    ]
