# Generated by Django 2.2.5 on 2020-12-23 01:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_auto_20201223_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityoccurrence',
            name='occurrences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Extra data asociated with this entity', verbose_name='occurrences'),
        ),
    ]
