# Generated by Django 2.2.5 on 2020-12-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_auto_20201223_0116'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, mid=''), fields=('mid',), name='unique_mid'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(condition=models.Q(mid=''), fields=('name', 'kind'), name='unique_name_kind'),
        ),
    ]
