# Generated by Django 2.2.5 on 2020-12-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_entity_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entityoccurrence',
            unique_together={('document', 'entity')},
        ),
    ]
