# Generated by Django 2.2.5 on 2021-01-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_auto_20201223_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='publish_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Scheduled time to make document public', null=True, verbose_name='publish at'),
        ),
    ]
