# Generated by Django 2.2.5 on 2021-02-16 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_auto_20210113_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='document',
            field=models.ForeignKey(help_text='The document this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='documents.Document', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='section',
            name='document',
            field=models.ForeignKey(help_text='The document this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='documents.Document', verbose_name='document'),
        ),
    ]
