# Generated by Django 2.2.5 on 2021-03-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0040_auto_20210216_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='solr_dirty',
            field=models.BooleanField(default=True, help_text='Tracks if the Solr Index is out of date with the SQL model', verbose_name='solr dirty'),
        ),
    ]
