# Generated by Django 2.2.5 on 2021-03-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0042_auto_20210317_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cache_dirty',
            field=models.BooleanField(default=False, help_text='A destructive operation is taking place and the CDN cache for this document should be invalidated when it is done processing', verbose_name='cache dirty'),
        ),
    ]
