# Generated by Django 2.2.5 on 2021-04-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0043_document_cache_dirty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('created_at',), 'permissions': (('share_document', 'Can share edit access to the document through a project'), ('process_document', 'Document processor - can set `page_count`, `page_spec`, and `status` through the API'), ('change_ownership_document', 'Can change the user or organization which owns the document'))},
        ),
    ]
