# Generated by Django 3.2.9 on 2021-11-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0044_auto_20210422_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='entity',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Extra data asociated with this entity', verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='entityoccurrence',
            name='occurrences',
            field=models.JSONField(default=dict, help_text='Extra data asociated with this entity', verbose_name='occurrences'),
        ),
    ]
