# Generated by Django 3.2.9 on 2022-03-07 14:34

# Django
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("documents", "0045_auto_20211102_1709")]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ("pk",),
                "permissions": (
                    (
                        "share_document",
                        "Can share edit access to the document through a project",
                    ),
                    (
                        "process_document",
                        "Document processor - can set `page_count`, `page_spec`, and `status` through the API",
                    ),
                    (
                        "change_ownership_document",
                        "Can change the user or organization which owns the document",
                    ),
                ),
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="document",
                    name="status",
                    field=models.IntegerField(
                        choices=[
                            (0, "Success"),
                            (1, "Readable"),
                            (2, "Pending"),
                            (3, "Error"),
                            (4, "No file"),
                            (5, "Deleted"),
                        ],
                        db_index=True,
                        default=4,
                        help_text="The processing status of this document",
                        verbose_name="status",
                    ),
                )
            ],
            database_operations=[
                AddIndexConcurrently(
                    model_name="document",
                    index=models.Index(
                        fields=["status"], name="documents_document_status_9de21ed2"
                    ),
                )
            ],
        ),
        AddIndexConcurrently(
            model_name="document",
            index=models.Index(
                condition=models.Q(
                    ("solr_dirty", True), models.Q(("status", 5), _negated=True)
                ),
                fields=["id"],
                name="solr_dirty",
            ),
        ),
    ]
