# Generated by Django 3.2.9 on 2022-05-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0047_alter_document_original_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='solr_dirty',
            field=models.BooleanField(default=True, help_text='Tracks if the Solr Index is out of date with the SQL model', verbose_name='solr dirty'),
        ),
    ]
