# Generated by Django 3.2.9 on 2022-10-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0049_document_delayed_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hide_from_google',
            field=models.BooleanField(default=False, help_text='Ask Google to not index this document', verbose_name='hide from google'),
        ),
    ]
