# Generated by Django 3.2.9 on 2023-03-03 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0050_document_noindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='revision_control',
            field=models.BooleanField(default=False, help_text='Enable revision control for this document - a copy of the PDF will be kept before any destructive action is taken', verbose_name='revision control'),
        ),
        migrations.AlterField(
            model_name='page',
            name='document',
            field=models.ForeignKey(help_text='The document this page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='documents.document', verbose_name='document'),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='version')),
                ('comment', models.CharField(max_length=255, verbose_name='comment')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.document', verbose_name='document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'unique_together': {('document', 'version')},
            },
        ),
    ]
