# Generated by Django 3.2.9 on 2023-02-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0050_document_noindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityoccurrence',
            name='document',
            field=models.ForeignKey(help_text='The document this entity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_entities_2', to='documents.document', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='page',
            name='document',
            field=models.ForeignKey(help_text='The document this page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='documents.document', verbose_name='document'),
        ),
    ]
