# Generated by Django 3.2.9 on 2023-05-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0051_auto_20230214_1451'),
        ('documents', '0051_auto_20230303_1923'),
    ]

    operations = [
    ]
