# Generated by Django 3.2.9 on 2023-06-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0052_merge_0051_auto_20230214_1451_0051_auto_20230303_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ('version',)},
        ),
        migrations.AddField(
            model_name='document',
            name='admin_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines and DocumentCloud search to not index this document (Admin override)', verbose_name='admin noindex'),
        ),
    ]
