# Generated by Django 3.2.9 on 2026-03-17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import documentcloud.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0053_auto_20230622_1623"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the saved search",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A name for the saved search",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "query",
                    models.TextField(
                        help_text="The search query string",
                        verbose_name="query",
                    ),
                ),
                (
                    "created_at",
                    documentcloud.core.fields.AutoCreatedField(
                        editable=False,
                        help_text="Timestamp of when the saved search was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    documentcloud.core.fields.AutoLastModifiedField(
                        editable=False,
                        help_text="Timestamp of when the saved search was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this saved search",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
