# Generated by Django 2.2.5 on 2019-09-26 19:45

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0005_entity_entitydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(blank=True, help_text='The user who created this collaboration', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of the project', max_length=255, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='A slug for the project which may be used in a URL', max_length=255, populate_from='title', verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='A description of the documents contained in this project', verbose_name='description')),
                ('private', models.BooleanField(default=False, help_text='Private projects may only be viewed by their collaborators', verbose_name='private')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the project was created', verbose_name='created at')),
                ('updated_at', documentcloud.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the project was last updated', verbose_name='updated at')),
                ('collaborators', models.ManyToManyField(related_name='projects', through='projects.Collaboration', to=settings.AUTH_USER_MODEL, verbose_name='collaborators')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_access', models.BooleanField(default=False, help_text='Whether collaborators on this project have edit access to this document', verbose_name='edit access')),
                ('document', models.ForeignKey(help_text='The document which belongs to the project', on_delete=django.db.models.deletion.CASCADE, to='documents.Document', verbose_name='document')),
                ('project', models.ForeignKey(help_text='The project which contains the document', on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(help_text='The documents in this project', related_name='projects', through='projects.ProjectMembership', to='documents.Document', verbose_name='documents'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(help_text='The user who created this project', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='project',
            field=models.ForeignKey(help_text='The project being collaborated on', on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='user',
            field=models.ForeignKey(help_text='The user collaborating on this project', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
