# Generated by Django 2.2.5 on 2020-01-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboration',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('slug',)},
        ),
        migrations.AlterModelOptions(
            name='projectmembership',
            options={'ordering': ('id',)},
        ),
    ]
