# Generated by Django 2.2.5 on 2020-02-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20200205_1535'),
        ('projects', '0002_auto_20200128_1418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('project', 'document')},
        ),
    ]
