# Generated by Django 2.2.5 on 2020-02-10 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20200210_1548'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaboration',
            unique_together={('project', 'user')},
        ),
    ]
