# Generated by Django 2.2.5 on 2020-02-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200210_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='access',
            field=models.IntegerField(choices=[(0, 'View'), (1, 'Edit'), (2, 'Admin')], default=0, help_text='The level of access granted to this collaborator', verbose_name='access'),
        ),
    ]
