# Generated by Django 2.2.5 on 2020-02-14 16:41

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("projects", "0005_collaboration_access")]

    operations = [
        migrations.RunSQL("ALTER SEQUENCE projects_project_id_seq RESTART WITH 200000")
    ]
