# Generated by Django 2.2.5 on 2020-04-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200214_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='edit_access',
            field=models.BooleanField(default=True, help_text='Whether collaborators on this project have edit access to this document', verbose_name='edit access'),
        ),
    ]
