# Generated by Django 2.2.5 on 2020-04-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200406_0048'),
        ('projects', '0007_auto_20200311_1936'),
    ]

    operations = [
    ]
