# Generated by Django 2.2.5 on 2020-04-29 01:21

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200407_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_duplicates=True, blank=True, editable=False, help_text='A slug for the project which may be used in a URL', max_length=255, populate_from='title', verbose_name='slug'),
        ),
    ]
