# Generated by Django 2.2.5 on 2021-04-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210216_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('slug',), 'permissions': (('add_remove_project', 'Can add & remove documents from a project'),)},
        ),
    ]
