# Generated by Django 4.2.2 on 2025-12-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210407_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('slug',), 'permissions': (('add_remove_project', 'Can add & remove documents from a project'), ('change_project_all', 'Can edit all fields on a project (not just pinned)'))},
        ),
    ]
