AWSTemplateFormatVersion: '2010-09-09'
Description: 'cloud-staging

  SAM template for PDF extraction and optical character recognition staging cloud functions

  '
Globals:
  Function:
    Environment:
      Variables:
        ENVIRONMENT: aws
        SERVERLESS: True
        REDIS_PROCESSING_URL: redis://3.233.63.186:6379/0
        REDIS_PROCESSING_PASSWORD: ZSU2bSA3jv3vyciYVqPzQMLBvycMXrOjh81T2dX4DGpH6l1tj54njwx3HJH5eeEgHZvNLPf8UrMismuW6ypiYJ29FUf21YJ0ldJqAXpszdEo4X88LBR0M2Pkb3pW1ESw
        API_CALLBACK: https://api.staging.documentcloud.org/api/
        PROCESSING_TOKEN: WcIzhlOLWWggyvXN82LAajAOZl3qgijpIgdeDH1iNeUnzo6mkVCveDLS8gWzEGun
        DOCUMENT_BUCKET: documentcloud-staging-files
        PDF_PROCESS_TOPIC: pdf-process-staging
        IMAGE_EXTRACT_TOPIC: image-extraction-staging
        OCR_TOPIC: ocr-extraction-staging
        EXTRACT_IMAGE_BATCH: 1
        AWS_ARN_PREFIX: arn:aws:sns:us-east-1:844030562261
        TIMEOUTS: 15,30,60,120
    Timeout: 180
    MemorySize: 3008
    VpcConfig:
      SecurityGroupIds:
        - sg-0063b8e6a0046dec8
      SubnetIds:
        - subnet-093cc6cb28a203621
        - subnet-092558d1765347ad9
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessPdfFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: main.process_pdf
      CodeUri: ./awsbin/info_and_image
      # Trigger function via HTTP
      Events:
        ProcessPdfApi:
          Type: Api
          Properties:
            Path: /process_pdf
            Method: POST
      Role: arn:aws:iam::844030562261:role/lambda-role

  ProcessPdfInternalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: main.process_pdf_internal
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Events:
        ProcessPdfApi:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:844030562261:pdf-process-staging
      Role: arn:aws:iam::844030562261:role/lambda-role

  ExtractImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: main.extract_image
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:844030562261:image-extraction-staging
      Role: arn:aws:iam::844030562261:role/lambda-role

  RunTesseractFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: main.run_tesseract
      CodeUri: ./awsbin/ocr
      Environment:
        Variables:
          LD_LIBRARY_PATH: /var/task/tesseract
      # Trigger function via SNS
      Events:
        OcrApi:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:844030562261:ocr-extraction-staging
      Role: arn:aws:iam::844030562261:role/lambda-role
