AWSTemplateFormatVersion: '2010-09-09'
Description: 'info-and-image-staging

  SAM template for cloud functions related to DocumentCloud

  '
Globals:
  Function:
    Environment:
      Variables:
        ENVIRONMENT: aws
        SERVERLESS: True
        EXTRACT_IMAGE_BATCH: "{{resolve:ssm:staging-EXTRACT_IMAGE_BATCH:latest}}"
        OCR_BATCH: "{{resolve:ssm:staging-OCR_BATCH:latest}}"
        REDIS_PROCESSING_URL: "{{resolve:ssm:staging-REDIS_PROCESSING_URL:latest}}"
        REDIS_PROCESSING_PASSWORD: "{{resolve:ssm:staging-REDIS_PROCESSING_PASSWORD:latest}}"
        API_CALLBACK: "{{resolve:ssm:staging-API_CALLBACK:latest}}"
        PROCESSING_TOKEN: "{{resolve:ssm:staging-PROCESSING_TOKEN:latest}}"
        DOCUMENT_BUCKET: "{{resolve:ssm:staging-DOCUMENT_BUCKET:latest}}"
        PDF_PROCESS_TOPIC: "{{resolve:ssm:staging-PDF_PROCESS_TOPIC:latest}}"
        IMAGE_EXTRACT_TOPIC: "{{resolve:ssm:staging-IMAGE_EXTRACT_TOPIC:latest}}"
        OCR_TOPIC: "{{resolve:ssm:staging-OCR_TOPIC:latest}}"
        SENTRY_DSN: "{{resolve:ssm:staging-SENTRY_DSN:latest}}"
        AWS_ARN_PREFIX: "{{resolve:ssm:staging-AWS_ARN_PREFIX:latest}}"
    Timeout: 300
    MemorySize: 3008
    VpcConfig:
      SecurityGroupIds:
        - sg-0063b8e6a0046dec8
      SubnetIds:
        - subnet-093cc6cb28a203621
        - subnet-092558d1765347ad9
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessDocFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: main.process_doc
      CodeUri: ./awsbin/utils
      # Trigger function via HTTP
      Environment:
        Variables:
          TIMEOUTS: 5,10,60
      Events:
        ProcessPdfApi:
          Type: Api
          Properties:
            Path: /process_doc
            Method: POST
      Role: arn:aws:iam::844030562261:role/lambda-role

  GetProgressFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: main.get_progress
      CodeUri: ./awsbin/utils
      # Trigger function via HTTP
      Environment:
        Variables:
          TIMEOUTS: 1,2,5
      Events:
        ProcessPdfApi:
          Type: Api
          Properties:
            Path: /get_progress
            Method: POST
      Role: arn:aws:iam::844030562261:role/lambda-role

  ProcessPdfFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: main.process_pdf
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: 60,120,180
      Events:
        ProcessPdfApi:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:844030562261:pdf-process-staging
      Role: arn:aws:iam::844030562261:role/lambda-role

  ExtractImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: main.extract_image
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: 60,120,240
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:844030562261:image-extraction-staging
      Role: arn:aws:iam::844030562261:role/lambda-role

  RedactDocFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: main.redact_doc
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: 60,120,240
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:844030562261:redact-doc-staging
      Role: arn:aws:iam::844030562261:role/lambda-role

  RunTesseractFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: main.run_tesseract
      CodeUri: ./awsbin/ocr
      Environment:
        Variables:
          LD_LIBRARY_PATH: /var/task/tesseract
          TIMEOUTS: 60,120,240
      # Trigger function via SNS
      Events:
        OcrApi:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:844030562261:ocr-extraction-staging
      Role: arn:aws:iam::844030562261:role/lambda-role
