AWSTemplateFormatVersion: "2010-09-09"
Description: "processing-stack

  SAM template for cloud functions related to DocumentCloud

  "
Globals:
  Function:
    Environment:
      Variables:
        ENVIRONMENT: aws
        SERVERLESS: True
        EXTRACT_IMAGE_BATCH: "{{resolve:ssm:/dc/{$ENV$}/lambdas/extract_image/batch:latest}}"
        OCR_BATCH: "{{resolve:ssm:/dc/{$ENV$}/lambdas/ocr/batch:latest}}"
        TEXT_POSITION_BATCH: "{{resolve:ssm:/dc/{$ENV$}/lambdas/text_position_extract/batch:latest}}"
        OCR_VERSION: "{{resolve:ssm:/dc/{$ENV$}/params/ocr_version:latest}}"
        OCR_DATA_DIRECTORY: "{{resolve:ssm:/dc/{$ENV$}/params/ocr_data_bucket:latest}}"
        REDIS_PROCESSING_URL: "{{resolve:ssm:/dc/{$ENV$}/params/redis_processing_url:latest}}"
        REDIS_PROCESSING_PASSWORD: "{{resolve:ssm:/dc/{$ENV$}/params/redis_processing_password:latest}}"
        REDIS_SOCKET_TIMEOUT: "{{resolve:ssm:/dc/{$ENV$}/params/redis_socket_timeout:latest}}"
        REDIS_SOCKET_CONNECT_TIMEOUT: "{{resolve:ssm:/dc/{$ENV$}/params/redis_socket_connect_timeout:latest}}"
        REDIS_HEALTH_CHECK_INTERVAL: "{{resolve:ssm:/dc/{$ENV$}/params/redis_health_check_interval:latest}}"
        API_CALLBACK: "{{resolve:ssm:/dc/{$ENV$}/params/api_callback:latest}}"
        PROCESSING_TOKEN: "{{resolve:ssm:/dc/{$ENV$}/params/processing_token:latest}}"
        DOCUMENT_BUCKET: "{{resolve:ssm:/dc/{$ENV$}/params/document_bucket:latest}}"
        PDF_PROCESS_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/pdf_process/topic:latest}}"
        PAGE_CACHE_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/page_cache/topic:latest}}"
        IMAGE_EXTRACT_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/extract_image/topic:latest}}"
        OCR_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/ocr/topic:latest}}"
        DOCUMENT_CONVERT_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/document_conversion/topic:latest}}"
        ASSEMBLE_TEXT_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/assemble_text/topic:latest}}"
        TEXT_POSITION_EXTRACT_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/text_position_extract/topic:latest}}"
        REDACT_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/redact_doc/topic:latest}}"
        START_IMPORT_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/start_import/topic:latest}}"
        IMPORT_DOCUMENT_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/import_document/topic:latest}}"
        FINISH_IMPORT_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/finish_import/topic:latest}}"
        MODIFY_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/modify_document/topic:latest}}"
        SIDEKICK_PREPROCESS_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/sidekick_preprocess/topic:latest}}"
        RETRY_ERROR_TOPIC: "{{resolve:ssm:/dc/{$ENV$}/lambdas/retry_errors/topic:latest}}"
        PDF_SIZE_LIMIT: "{{resolve:ssm:/dc/{$ENV$}/params/pdf_size_limit:latest}}"
        BLOCK_SIZE: "{{resolve:ssm:/dc/{$ENV$}/params/block_size:latest}}"
        IMPORT_DIR: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/import_dir:latest}}"
        IMPORT_BUCKET: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/import_bucket:latest}}"
        SENTRY_DSN: "{{resolve:ssm:/dc/{$ENV$}/params/sentry_dsn:latest}}"
        AWS_ARN_PREFIX: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}"
        VOCAB_SIZE: "{{resolve:ssm:/dc/{$ENV$}/params/vocab_size:latest}}"
        EMBEDDING_DIR: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/embedding_dir:latest}}"
    Timeout: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/timeout:latest}}"
    MemorySize: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/memory_size:latest}}"
    VpcConfig:
      SecurityGroupIds:
        - "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/security_group_ids:latest}}"
      SubnetIds: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/subnet_ids:latest}}"
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessDocFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.process_doc
      CodeUri: ./awsbin/utils
      # Trigger function via HTTP
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/process_doc/timeout:latest}}"
      Events:
        ProcessPdfApi:
          Type: Api
          Properties:
            Path: /process_doc
            Method: POST
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  GetProgressFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.get_progress
      CodeUri: ./awsbin/utils
      # Trigger function via HTTP
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/get_progress/timeout:latest}}"
      Events:
        ProcessPdfApi:
          Type: Api
          Properties:
            Path: /get_progress
            Method: POST
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  ImportDocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.import_documents
      CodeUri: ./awsbin/utils
      # Trigger function via HTTP
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/import_documents/timeout:latest}}"
      Events:
        ProcessPdfApi:
          Type: Api
          Properties:
            Path: /import_documents
            Method: POST
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  SidekickFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.sidekick
      CodeUri: ./awsbin/utils
      # Trigger function via HTTP
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/sidekick/timeout:latest}}"
      Events:
        ProcessPdfApi:
          Type: Api
          Properties:
            Path: /sidekick
            Method: POST
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  ProcessPdfFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.process_pdf
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/process_pdf/timeout:latest}}"
      Events:
        ProcessPdfApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/pdf_process/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  ProcessPageCacheFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.process_page_cache
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/page_cache/timeout:latest}}"
      Events:
        ProcessPdfApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/page_cache/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  ExtractImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.extract_image
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/extract_image/timeout:latest}}"
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/extract_image/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  RedactDocFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.redact_doc
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/redact_doc/timeout:latest}}"
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/redact_doc/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  RunTesseractFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.run_tesseract
      CodeUri: ./awsbin/ocr
      Environment:
        Variables:
          LD_LIBRARY_PATH: /var/task/tesseract
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/ocr/timeout:latest}}"
          OCR_TOPIC: ocr-extraction-{$ENV$}
      # Trigger function via SNS
      Events:
        OcrApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":ocr-extraction-{$ENV$}
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  ConvertDocFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.run_document_conversion
      CodeUri: ./awsbin/document_conversion
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/document_conversion/timeout:latest}}"
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/document_conversion/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  AssembleTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.assemble_page_text
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/assemble_text/timeout:latest}}"
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/assemble_text/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  ExtractTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.extract_text_position
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/text_position_extract/timeout:latest}}"
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/text_position_extract/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  StartImportFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.start_import
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/start_import/timeout:latest}}"
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/start_import/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  ImportDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.import_document
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/import_document/timeout:latest}}"
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/import_document/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  FinishImportFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.finish_import
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/finish_import/timeout:latest}}"
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/finish_import/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  ModifyDocFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.modify_doc
      CodeUri: ./awsbin/info_and_image
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/modify_document/timeout:latest}}"
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/modify_document/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"
      
  SidekickPreprocessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.preprocess
      # https://github.com/model-zoo/scikit-learn-lambda/blob/master/layers.csv
      Layers: ["arn:aws:lambda:us-east-1:446751924810:layer:python-3-7-scikit-learn-0-23-1:2"]
      CodeUri: ./awsbin/sidekick
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/sidekick_preprocess/timeout:latest}}"
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/sidekick_preprocess/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"

  RetryErrorsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Handler: main.retry_errors
      CodeUri: ./awsbin/utils
      # Trigger function via SNS
      Environment:
        Variables:
          TIMEOUTS: "{{resolve:ssm:/dc/{$ENV$}/lambdas/retry_errors/timeout:latest}}"
      Events:
        ExtractImageApi:
          Type: SNS
          Properties:
            Topic: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/aws_arn_prefix:latest}}":"{{resolve:ssm:/dc/{$ENV$}/lambdas/retry_errors/topic:latest}}"
      Role: "{{resolve:ssm:/dc/{$ENV$}/lambdas/config/role:latest}}"
