# Generated by Django 3.2.9 on 2022-02-22 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.SQUARELET_ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The add-on's name", max_length=255, verbose_name='name')),
                ('repository', models.CharField(help_text="The add-on's GitHub repository", max_length=140, verbose_name='repository')),
                ('github_token', models.CharField(help_text="The token to access the add-on's GitHub repository", max_length=40, verbose_name='github token')),
                ('parameters', models.JSONField(help_text='The parameters for this add-on', verbose_name='parameters')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the document was created', verbose_name='created at')),
                ('updated_at', documentcloud.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the document was last updated', verbose_name='updated at')),
                ('organization', models.ForeignKey(help_text='The organization this add-on was created within', on_delete=django.db.models.deletion.PROTECT, related_name='addons', to=settings.SQUARELET_ORGANIZATION_MODEL, verbose_name='organization')),
                ('user', models.ForeignKey(help_text='The user who created this add-on', on_delete=django.db.models.deletion.PROTECT, related_name='addons', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='AddOnRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique ID to track add-on runs', unique=True, verbose_name='UUID')),
                ('run_id', models.IntegerField(help_text='The GitHub Action run_id for this run', null=True, unique=True, verbose_name='run_id')),
                ('status', models.CharField(default='queued', help_text='The status of this run', max_length=25, verbose_name='status')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='The progress as a percent done of this run', verbose_name='progress')),
                ('message', models.CharField(default='', help_text='A progress message for the user while the run is in progress', max_length=255, verbose_name='message')),
                ('file_name', models.CharField(default='', help_text='Path to uploaded file on S3', max_length=255, verbose_name='file_name')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the document was created', verbose_name='created at')),
                ('updated_at', documentcloud.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the document was last updated', verbose_name='updated at')),
                ('addon', models.ForeignKey(help_text='The add-on which was ran', on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='addons.addon', verbose_name='add-on')),
                ('user', models.ForeignKey(help_text='The user who ran this add-on', on_delete=django.db.models.deletion.PROTECT, related_name='addon_runs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
