# Generated by Django 3.2.9 on 2022-02-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonrun',
            name='dismissed',
            field=models.BooleanField(default=False, help_text='If this run has been dismissed from view and should no longer be shown to the user', verbose_name='dismissed'),
        ),
    ]
