# Generated by Django 3.2.9 on 2022-03-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0002_addonrun_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='error',
            field=models.BooleanField(default=False, help_text='There was an error with the configuration file', verbose_name='error'),
        ),
    ]
