# Generated by Django 3.2.9 on 2022-03-30 19:08

# Django
from django.db import migrations


def make_add_ons_public(apps, schema_editor):
    AddOn = apps.get_model("addons", "AddOn")
    # 0 is public
    AddOn.objects.update(access=0)


class Migration(migrations.Migration):

    dependencies = [("addons", "0004_addon_access")]

    operations = [migrations.RunPython(make_add_ons_public, migrations.RunPython.noop)]
