# Generated by Django 3.2.9 on 2022-04-04 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addons', '0005_auto_20220330_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(help_text='The ID for the GitHub account', verbose_name='uid')),
                ('token', models.CharField(help_text='The GitHub token', max_length=255, verbose_name='token')),
                ('user', models.ForeignKey(help_text='The user associated with this GitHub account', on_delete=django.db.models.deletion.PROTECT, related_name='github_accounts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='addon',
            name='github_account',
            field=models.ForeignKey(help_text='The GitHub account that added this add-on', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addons', to='addons.githubaccount', verbose_name='github account'),
        ),
    ]
