# Generated by Django 3.2.9 on 2022-04-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0007_auto_20220407_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='github_token',
            new_name='_github_token',
        ),
    ]
