# Generated by Django 3.2.9 on 2022-04-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0010_auto_20220411_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='user',
            new_name='_user',
        ),
        migrations.AddField(
            model_name='addon',
            name='github_installation',
            field=models.ForeignKey(help_text='The GitHub installation that contains this add-on', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addons', to='addons.githubinstallation', verbose_name='github installation'),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='name',
            field=models.CharField(default='', help_text='The GitHub username', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubinstallation',
            name='name',
            field=models.CharField(default='', help_text='The GitHub name of the user or organization the app was installed for', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubaccount',
            name='uid',
            field=models.IntegerField(help_text='The ID for the GitHub account', unique=True, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='githubinstallation',
            name='iid',
            field=models.IntegerField(help_text='The ID for the GitHub installation', unique=True, verbose_name='iid'),
        ),
    ]
