# Generated by Django 3.2.9 on 2022-04-12 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.SQUARELET_ORGANIZATION_MODEL),
        ('addons', '0011_auto_20220411_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='organization',
            field=models.ForeignKey(help_text='The organization this add-on was created within', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addons', to=settings.SQUARELET_ORGANIZATION_MODEL, verbose_name='organization'),
        ),
    ]
