# Generated by Django 3.2.9 on 2022-04-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0012_alter_addon_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubinstallation',
            name='removed',
            field=models.BooleanField(default=False, help_text='This installation was removed', verbose_name='removed'),
        ),
    ]
