# Generated by Django 3.2.9 on 2022-04-12 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addons', '0013_githubinstallation_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='_user',
            field=models.ForeignKey(db_column='user', help_text='The user who created this add-on', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addons', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
