# Generated by Django 3.2.9 on 2022-04-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0014_alter_addon__user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='_user',
        ),
        migrations.AlterField(
            model_name='addon',
            name='github_account',
            field=models.ForeignKey(help_text='The GitHub account that added this add-on', on_delete=django.db.models.deletion.PROTECT, related_name='addons', to='addons.githubaccount', verbose_name='github account'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='github_installation',
            field=models.ForeignKey(help_text='The GitHub installation that contains this add-on', on_delete=django.db.models.deletion.PROTECT, related_name='addons', to='addons.githubinstallation', verbose_name='github installation'),
        ),
    ]
