# Generated by Django 3.2.9 on 2022-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0016_remove_addon__github_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonrun',
            name='run_id',
            field=models.BigIntegerField(help_text='The GitHub Action run_id for this run', null=True, unique=True, verbose_name='run_id'),
        ),
    ]
