# Generated by Django 3.2.9 on 2022-05-05 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addons', '0018_alter_addon_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='created_at',
            field=documentcloud.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the add-on was created', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='parameters',
            field=models.JSONField(default=dict, help_text='The parameters for this add-on', verbose_name='parameters'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='updated_at',
            field=documentcloud.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the add-on was last updated', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='addonrun',
            name='created_at',
            field=documentcloud.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the add-on was ran', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='addonrun',
            name='updated_at',
            field=documentcloud.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the add-on run was last updated', verbose_name='updated at'),
        ),
        migrations.CreateModel(
            name='AddOnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict, help_text='The user supplied parameters to run the add-on with', verbose_name='parameters')),
                ('event', models.IntegerField(choices=[(0, 'Hourly'), (1, 'Daily'), (2, 'Weekly'), (3, 'Upload')], help_text='The event to trigger the add-on run', verbose_name='event')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the add-on event was created', verbose_name='created at')),
                ('updated_at', documentcloud.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the add-on event was last updated', verbose_name='updated at')),
                ('addon', models.ForeignKey(help_text='The add-on to run', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='addons.addon', verbose_name='add-on')),
                ('user', models.ForeignKey(help_text='The user who defined this event', on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='addonrun',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The add-on event which triggered this run', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='addons.addonevent', verbose_name='event'),
        ),
    ]
