# Generated by Django 3.2.9 on 2022-05-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0019_auto_20220505_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonevent',
            name='event',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Hourly'), (2, 'Daily'), (3, 'Weekly'), (4, 'Upload')], help_text='The event to trigger the add-on run', verbose_name='event'),
        ),
    ]
