# Generated by Django 3.2.9 on 2022-10-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0021_addonevent_scratch'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonrun',
            name='comment',
            field=models.CharField(default='', help_text='A comment from the user on how this run went', max_length=255, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='addonrun',
            name='rating',
            field=models.SmallIntegerField(choices=[(-1, 'Thumbs Down'), (0, ''), (1, 'Thumbs Up')], default=0, help_text='A rating from the user on how this run went', verbose_name='rating'),
        ),
    ]
