# Generated by Django 3.2.9 on 2023-03-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0022_auto_20221019_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='default',
            field=models.BooleanField(default=False, help_text='This add-on is enabled by default', verbose_name='default'),
        ),
        migrations.AddField(
            model_name='addon',
            name='featured',
            field=models.BooleanField(default=False, help_text='This add-on is featured in the browse add-on dialog', verbose_name='featured'),
        ),
    ]
