# Generated by Django 4.2.2 on 2023-08-01 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addons', '0023_auto_20230321_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique ID to track add-on files', unique=True, verbose_name='UUID')),
                ('created_at', documentcloud.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the add-on file was created', verbose_name='created at')),
                ('user', models.ForeignKey(help_text='The user who uploaded this file', on_delete=django.db.models.deletion.PROTECT, related_name='addon_files', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
