# Generated by Django 4.2.2 on 2023-08-18 19:23

from django.db import migrations
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("addons", "0023_auto_20230321_1452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addonrun",
            name="created_at",
            field=documentcloud.core.fields.AutoCreatedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="Timestamp of when the add-on was ran",
                verbose_name="created at",
            ),
        ),
    ]
