# Generated by Django 4.2.2 on 2023-11-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0024_alter_addonrun_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonrun',
            name='credits_spent',
            field=models.IntegerField(default=0, help_text='The amount of premium credits spent by this run', verbose_name='credits spent'),
        ),
    ]
