# Generated by Django 4.2.2 on 2024-04-01 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addons', '0025_addonrun_credits_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnDisableLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', documentcloud.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the add-on event was last updated', verbose_name='updated at')),
                ('previous_event_state', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Hourly'), (2, 'Daily'), (3, 'Weekly'), (4, 'Upload')], help_text='The event state of the Add-On before disable', verbose_name='previous event state')),
                ('addon', models.ForeignKey(help_text='The add-on which was ran', on_delete=django.db.models.deletion.PROTECT, related_name='addon_disable_log', to='addons.addon', verbose_name='add-on')),
                ('user', models.ForeignKey(help_text='The user who defined this event', on_delete=django.db.models.deletion.PROTECT, related_name='addon_disable_log', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Add-On Disable Log',
            },
        ),
    ]
