# Generated by Django 4.2.2 on 2024-04-05 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("addons", "0025_addonrun_credits_spent"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddOnDisableLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Hourly"),
                            (2, "Daily"),
                            (3, "Weekly"),
                            (4, "Upload"),
                        ],
                        help_text="The current event state of the Add-On",
                        verbose_name="event",
                    ),
                ),
                (
                    "created_at",
                    documentcloud.core.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp of when the add-on disable log was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "previous_event_state",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Hourly"),
                            (2, "Daily"),
                            (3, "Weekly"),
                            (4, "Upload"),
                        ],
                        help_text="The event state of the Add-On before disable",
                        verbose_name="previous event state",
                    ),
                ),
                (
                    "addon_event",
                    models.ForeignKey(
                        help_text="Reference to the Add-On Event",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disable_logs",
                        to="addons.addonevent",
                        verbose_name="event reference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Add-On Disable Log",
            },
        ),
    ]
