# Generated by Django 4.2.2 on 2024-07-24 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documentcloud.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.SQUARELET_ORGANIZATION_MODEL),
        ("addons", "0026_addondisablelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualAddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access",
                    models.IntegerField(
                        choices=[
                            (0, "Public"),
                            (1, "Organization"),
                            (2, "Private"),
                            (3, "Invisible"),
                        ],
                        default=2,
                        help_text="Designates who may access this document by default",
                        verbose_name="access",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The visual add-on's name",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, verbose_name="slug")),
                (
                    "url",
                    models.URLField(
                        help_text="URL of the Visual AddOn", verbose_name="URL"
                    ),
                ),
                (
                    "created_at",
                    documentcloud.core.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp of when the add-on was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    documentcloud.core.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp of when the add-on was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization that owns this visual add-on",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visual_addons",
                        to=settings.SQUARELET_ORGANIZATION_MODEL,
                        verbose_name="organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this visual add-on",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visual_addons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
