# Generated by Django 4.2.2 on 2026-04-29 16:43

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("addons", "0027_visualaddon"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="addonevent",
            index=models.Index(
                models.F("parameters__site"),
                condition=models.Q(("parameters__has_key", "site")),
                name="addonevent_param_site_idx",
            ),
        ),
    ]
