# Generated by Django 4.2.2 on 2026-05-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addons", "0028_addonevent_addonevent_param_site_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonrun",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Field to store arbitrary per-run data",
                null=True,
                verbose_name="data",
            ),
        ),
    ]
