# Generated by Django 4.2.2 on 2026-06-08 16:21

from django.db import migrations, models
import documentcloud.addons.models


class Migration(migrations.Migration):

    dependencies = [
        ("addons", "0029_addonrun_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="addonevent",
            index=models.Index(
                documentcloud.addons.models.SiteHost("parameters"),
                condition=models.Q(("parameters__has_key", "site")),
                name="addonevent_site_host_idx",
            ),
        ),
    ]
