# Generated by Django 4.2.2 on 2026-06-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addons", "0029_addonrun_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubaccount",
            name="token",
            field=models.CharField(
                help_text="The GitHub token", max_length=1024, verbose_name="token"
            ),
        ),
    ]
