# Generated by Django 4.2.2 on 2026-06-08

from django.contrib.postgres.operations import (
    AddIndexConcurrently,
    RemoveIndexConcurrently,
)
from django.db import migrations, models
import django.db.models.fields.json
import django.db.models.functions.text
import documentcloud.addons.models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("addons", "0029_addonrun_data"),
    ]

    operations = [
        # index the `site` origin (scheme + host) for the `domain` filter
        AddIndexConcurrently(
            model_name="addonevent",
            index=models.Index(
                documentcloud.addons.models.SiteOrigin("parameters"),
                condition=models.Q(("parameters__has_key", "site")),
                name="addonevent_site_origin_idx",
            ),
        ),
        # rebuild the `site` index as UPPER(...) so the case-insensitive
        # (iexact) `site` filter can use it
        RemoveIndexConcurrently(
            model_name="addonevent",
            name="addonevent_param_site_idx",
        ),
        AddIndexConcurrently(
            model_name="addonevent",
            index=models.Index(
                django.db.models.functions.text.Upper(
                    django.db.models.fields.json.KeyTextTransform("site", "parameters")
                ),
                condition=models.Q(("parameters__has_key", "site")),
                name="addonevent_param_site_idx",
            ),
        ),
    ]
