# Generated by Django 4.2.2 on 2026-06-08 19:10

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models
import documentcloud.addons.models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("addons", "0029_addonrun_data"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="addonevent",
            index=models.Index(
                documentcloud.addons.models.SiteOrigin("parameters"),
                condition=models.Q(("parameters__has_key", "site")),
                name="addonevent_site_origin_idx",
            ),
        ),
    ]
