# Generated by Django 5.2.13 on 2026-07-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addons", "0030_addonevent_site_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonevent",
            name="dismissed",
            field=models.BooleanField(
                default=False,
                help_text="If this event has been dismissed from view and should no longer be shown to the user",
                verbose_name="dismissed",
            ),
        ),
    ]
