# Generated by Django 4.2.2 on 2026-06-08 19:30

from django.db import migrations, models
import django.db.models.fields.json
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("addons", "0030_addonevent_addonevent_site_origin_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="addonevent",
            name="addonevent_param_site_idx",
        ),
        migrations.AddIndex(
            model_name="addonevent",
            index=models.Index(
                django.db.models.functions.text.Upper(
                    django.db.models.fields.json.KeyTextTransform("site", "parameters")
                ),
                condition=models.Q(("parameters__has_key", "site")),
                name="addonevent_param_site_idx",
            ),
        ),
    ]
