# Generated by Django 5.2.15 on 2026-09-18 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addons", "0031_addonevent_dismissed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="addonrun",
            index=models.Index(fields=["user", "-id"], name="addonrun_user_id_idx"),
        ),
    ]
