# Generated by Django 5.2.15 on 2026-09-22 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addons", "0032_addonrun_addonrun_user_id_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="addonrun",
            name="addonrun_user_id_idx",
        ),
        migrations.AddIndex(
            model_name="addonrun",
            index=models.Index(
                fields=["user", "-created_at"], name="addonrun_user_created_idx"
            ),
        ),
    ]
