# Generated by Django 2.2.5 on 2020-03-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200214_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_language',
            field=models.CharField(blank=True, choices=[('ara', 'Arabic'), ('zho', 'Chinese (Simplified)'), ('tra', 'Chinese (Traditional)'), ('hrv', 'Croatian'), ('dan', 'Danish'), ('nld', 'Dutch'), ('eng', 'English'), ('fra', 'French'), ('deu', 'German'), ('heb', 'Hebrew'), ('hun', 'Hungarian'), ('ind', 'Indonesian'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nor', 'Norwegian'), ('por', 'Portuguese'), ('ron', 'Romanian'), ('rus', 'Russian'), ('spa', 'Spanish'), ('swe', 'Swedish'), ('ukr', 'Ukrainian')], default='eng', help_text='The default language for documents uploaded by this user', max_length=3, verbose_name='document language'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('ara', 'Arabic'), ('zho', 'Chinese (Simplified)'), ('tra', 'Chinese (Traditional)'), ('hrv', 'Croatian'), ('dan', 'Danish'), ('nld', 'Dutch'), ('eng', 'English'), ('fra', 'French'), ('deu', 'German'), ('heb', 'Hebrew'), ('hun', 'Hungarian'), ('ind', 'Indonesian'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nor', 'Norwegian'), ('por', 'Portuguese'), ('ron', 'Romanian'), ('rus', 'Russian'), ('spa', 'Spanish'), ('swe', 'Swedish'), ('ukr', 'Ukrainian')], default='eng', help_text='The interface language for this user', max_length=3, verbose_name='language'),
        ),
    ]
