# Generated by Django 2.2.5 on 2020-05-23 15:34

from django.db import migrations
import django.utils.timezone
import squarelet_auth.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200306_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=squarelet_auth.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the user was created', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=squarelet_auth.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the user was last updated', verbose_name='updated at'),
        ),
    ]
