# Generated by Django 3.2.9 on 2022-03-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0005_auto_20220330_1908'),
        ('users', '0007_auto_20211102_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_addons',
            field=models.ManyToManyField(help_text='Add-Ons shown for this user', related_name='users', to='addons.AddOn', verbose_name='active add-ons'),
        ),
    ]
