# Generated by Django 3.2.9 on 2022-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_active_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mailkey',
            field=models.UUIDField(help_text='Mail key for uploading documents via email', null=True, verbose_name='mailkey'),
        ),
    ]
