# Generated by Django 4.2.2 on 2023-06-30 14:57

# Django
from django.contrib.postgres.operations import CreateCollation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_mailkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Public bio for the user, in Markdown",
                verbose_name="bio",
            ),
        ),
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_collation="case_insensitive",
                help_text="The user's primary email address",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_collation="case_insensitive",
                help_text="A unique public identifier for the user",
                max_length=150,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
