# Generated by Django 5.2.13 on 2026-04-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_default_pinned_projects"),
        ("users", "0013_user_active_addons"),
    ]

    operations = []
