# Generated by Django 2.2.5 on 2019-09-11 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('minimum_users', models.PositiveSmallIntegerField(default=1)),
                ('base_pages', models.PositiveSmallIntegerField(default=0)),
                ('pages_per_user', models.PositiveSmallIntegerField(default=0)),
                ('feature_level', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('private', models.BooleanField(default=False)),
                ('individual', models.BooleanField(default=True)),
                ('card', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=255)),
                ('pages_per_month', models.IntegerField(default=0, help_text='How many monthly pages this organization gets each month')),
                ('monthly_pages', models.IntegerField(default=0, help_text='How many recurring monthly pages are left for this month - these do not roll over and are just reset to `pages_per_month` on `date_update`')),
                ('number_pages', models.IntegerField(default=0, help_text='How many individually purchased pages this organization has - these never expire and are unaffected by the monthly roll over')),
                ('date_update', models.DateField(null=True)),
                ('payment_failed', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.Plan')),
            ],
        ),
    ]
