# Generated by Django 2.2.5 on 2020-05-23 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20200306_2000'),
        ('squarelet_auth_organizations', '0002_auto_20200423_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(help_text='An organization being linked to a user', on_delete=django.db.models.deletion.CASCADE, related_name='memberships_old', to=settings.SQUARELET_ORGANIZATION_MODEL, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(help_text='A user being linked to an organization', on_delete=django.db.models.deletion.CASCADE, related_name='memberships_old', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='date_update',
            field=models.DateField(help_text='The date when this organizations monthly resources will be refreshed', null=True, verbose_name='date update'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(help_text='The subscription type for this organization', null=True, on_delete=django.db.models.deletion.PROTECT, to='squarelet_auth_organizations.Plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(help_text='The users who are members of this organization', related_name='organizations', through='squarelet_auth_organizations.Membership', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
