# Generated by Django 2.2.5 on 2020-05-26 13:36

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squarelet_auth_organizations", "0002_auto_20200423_1008"),
        ("organizations", "0005_auto_20200526_1332"),
    ]

    operations = [
        # name clash for foreign key index
        migrations.RunSQL(
            sql="ALTER INDEX organizations_organization_plan_id_b7b3b9c5 RENAME TO "
            "organizations_organization_plan_old_id_b7b3b9c5",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="organization",
            name="plan",
            field=models.ForeignKey(
                help_text="The subscription type for this organization",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="squarelet_auth_organizations.Plan",
                verbose_name="plan",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="date_update",
            field=models.DateField(
                help_text="The date when this organizations monthly resources will be refreshed",
                null=True,
                verbose_name="date update",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="users",
            field=models.ManyToManyField(
                help_text="The users who are members of this organization",
                related_name="organizations",
                through="squarelet_auth_organizations.Membership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="users",
            ),
        ),
    ]
