# Generated by Django 2.2.5 on 2020-05-26 13:38

# Django
from django.db import migrations


def convert_plans(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    OldPlan = apps.get_model("organizations", "Plan")
    NewPlan = apps.get_model("squarelet_auth_organizations", "Plan")

    for old_plan in OldPlan.objects.all():
        new_plan = NewPlan.objects.create(
            name=old_plan.name,
            slug=old_plan.slug,
            resources={
                "minimum_users": old_plan.minimum_users,
                "base_pages": old_plan.base_pages,
                "pages_per_user": old_plan.pages_per_user,
                "feature_level": old_plan.feature_level,
            },
        )
        Organization.objects.filter(plan_old=old_plan).update(plan=new_plan)


def delete_new_plans(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    NewPlan = apps.get_model("squarelet_auth_organizations", "Plan")
    Organization.objects.update(plan=None)
    NewPlan.objects.all().delete()


def convert_memberships(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    OldMembership = apps.get_model("organizations", "Membership")
    NewMembership = apps.get_model("squarelet_auth_organizations", "Membership")

    new_memberships = []
    for old_membership in OldMembership.objects.all():
        new_memberships.append(
            NewMembership(
                user=old_membership.user,
                organization=old_membership.organization,
                active=old_membership.active,
                admin=old_membership.admin,
            )
        )
    NewMembership.objects.bulk_create(new_memberships)


def delete_new_memberships(apps, schema_editor):
    NewMembership = apps.get_model("squarelet_auth_organizations", "Membership")
    NewMembership.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("squarelet_auth_organizations", "0003_plan_resources"),
        ("organizations", "0006_auto_20200526_1336"),
    ]

    operations = [
        migrations.RunPython(convert_plans, delete_new_plans),
        migrations.RunPython(convert_memberships, delete_new_memberships),
    ]
