# Generated by Django 2.2.5 on 2020-05-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20200526_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='plan_old',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
