# Generated by Django 2.2.5 on 2020-05-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squarelet_auth_organizations', '0005_auto_20200527_0921'),
        ('organizations', '0008_auto_20200526_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='entitlement',
            field=models.ForeignKey(help_text='The subscription type for this organization', null=True, on_delete=django.db.models.deletion.PROTECT, to='squarelet_auth_organizations.Entitlement', verbose_name='entitlement'),
        ),
    ]
