# Generated by Django 2.2.5 on 2020-05-28 12:44

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("organizations", "0010_auto_20200527_1732")]
    run_before = [("squarelet_auth_organizations", "0006_auto_20200527_1646")]

    operations = [migrations.RemoveField(model_name="organization", name="plan")]
