# Generated by Django 3.2.9 on 2022-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20211102_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='monthly_pages',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='number_pages',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='pages_per_month',
        ),
        migrations.AddField(
            model_name='organization',
            name='ai_credits_per_month',
            field=models.IntegerField(default=0, help_text='How many monthly AI credits this organization gets each month', verbose_name='AI credits per month'),
        ),
        migrations.AddField(
            model_name='organization',
            name='monthly_ai_credits',
            field=models.IntegerField(default=0, help_text='How many recurring monthly AI credits are left for this month - these do not roll over and are just reset to `ai_credits_per_month` on `date_update`', verbose_name='monthly AI credits'),
        ),
        migrations.AddField(
            model_name='organization',
            name='number_ai_credits',
            field=models.IntegerField(default=0, help_text='How many individually purchased AI credits this organization has - these never expire and are unaffected by the monthly roll over', verbose_name='number AI credits'),
        ),
    ]
