# Generated by Django 4.2.2 on 2023-11-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_aicreditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicreditlog',
            options={'verbose_name': 'AI Credit Log'},
        ),
    ]
