# Generated by Django 4.2.2 on 2025-05-01 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0016_alter_aicreditlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="merged",
            field=models.ForeignKey(
                blank=True,
                help_text="The agency this agency was merged in to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.SQUARELET_ORGANIZATION_MODEL,
            ),
        ),
    ]
