# Generated by Django 4.2.2 on 2025-12-22 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_organization_merged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='merged',
            field=models.ForeignKey(blank=True, help_text='The organization this organization was merged in to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.SQUARELET_ORGANIZATION_MODEL),
        ),
    ]
