# Generated by Django 4.2.2 on 2026-01-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_organization_members_organization_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='members',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='share_resources',
        ),
    ]
