# Generated by Django 4.2.2 on 2026-01-21 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0020_remove_organization_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organizations which are members of this organization (useful for trade associations or other member groups)",
                related_name="groups",
                to=settings.SQUARELET_ORGANIZATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent organization",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to=settings.SQUARELET_ORGANIZATION_MODEL,
                verbose_name="parent",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="share_resources",
            field=models.BooleanField(
                default=True,
                help_text="Share resources (subscriptions, credits) with all children and member organizations. Global toggle that applies to all relationships.",
                verbose_name="share resources",
            ),
        ),
    ]
