# Generated by Django 5.2.13 on 2026-07-22 19:32

import django.utils.timezone
import documentcloud.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0021_organization_members_organization_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="created_at",
            field=documentcloud.core.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Timestamp of when the organization was created",
                verbose_name="created at",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=documentcloud.core.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Timestamp of when the organization was last updated",
                verbose_name="updated at",
            ),
        ),
    ]
