# Generated by Django 5.2.15 on 2026-08-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0023_organizationstats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationstats",
            name="last_ai_credit_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
