# Generated by Django 5.2.15 on 2026-09-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0024_organizationstats_last_ai_credit_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationstats",
            name="recent_upload_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="organizationstats",
            name="total_documents",
            field=models.IntegerField(default=0),
        ),
    ]
