# Generated by Django 2.2.5 on 2021-07-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0012_auto_20210407_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidekick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Uninitialized'), (1, 'Processing'), (2, 'Initialized'), (3, 'Error')], default=0, help_text='The status of this sidekick', verbose_name='status')),
                ('tag_name', models.CharField(help_text='The name of the tag to use to associate a document as a positive or negative match for this sidekick', max_length=50, verbose_name='tag name')),
                ('project', models.OneToOneField(help_text='The project this sidekick is for', on_delete=django.db.models.deletion.CASCADE, related_name='sidekick', to='projects.Project', verbose_name='project')),
            ],
        ),
    ]
