# Generated by Django 2.2.5 on 2021-07-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidekick', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidekick',
            name='tag_name',
        ),
        migrations.AlterField(
            model_name='sidekick',
            name='status',
            field=models.IntegerField(choices=[(0, 'Success'), (1, 'Pending'), (2, 'Error')], default=1, help_text='The status of this sidekick', verbose_name='status'),
        ),
    ]
